name: Push Workflow

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
            distribution: 'temurin'
            java-version: 11
            cache: 'gradle'
      - name: Run Unit Tests
        id: run-unit-tests
        run: ./gradlew testDebugUnitTest